apiVersion: v1
kind: Service
metadata:
  name: lb-wordpress
spec:
  type: NodePort
  ports:
  - name: lb-wordpress
    port: 80
    targetPort: 80
    nodePort: 32095
    protocol: TCP
  selector:
    app: wordpress
