apiVersion: v1
kind: Service
metadata:  
  name: wordpress-srv-ext
spec:
  type: NodePort
  ports:  
  - name: wordpress-srv-ext
    port: 80
    targetPort: 80
    nodePort: 30042
    protocol: TCP
  selector:    
    app: wordpress
