apiVersion: v1
kind: Service
metadata:  
  name: cassandra-lb2
spec:
  type: NodePort
  ports:  
  - name: cassandra
    port: 9042
    targetPort: 9042
    nodePort: 90042
    protocol: TCP
  selector:    
    app: cassandra
